export interface Row {
    label: string;
    value?: string;
    indent?: boolean;
    header?: boolean;
}

export interface Section {
    title: string;
    rows: Row[];
}

export const sections: Section[] = [
    {
        title: 'Generelt',
        rows: [
            { label: 'Generator:', header: true },
            { label: 'Øvre pivotbolt', value: '54', indent: true },
            { label: 'Nedre justeringsbrakettbolt', value: '34', indent: true },
            { label: 'Tappeplugg kjølevæske', value: '20' },
            { label: 'Tappeplugg motorolje', value: '30' },
            { label: 'Tappeplugg girkasse', value: '29' },
            { label: 'Påfyllingsplugg girkasse', value: '39' },
            { label: 'Tenningsspoler', value: '10' },
            { label: 'Hjulbolter', value: '100' },
            { label: 'Tennplugger', value: '25' },
        ],
    },
    {
        title: 'Motor',
        rows: [
            { label: 'Veivstakelagerbolter:', header: true },
            { label: 'Trinn 1', value: '15', indent: true },
            { label: 'Trinn 2', value: '+90°', indent: true },
            { label: "Kamakselens lagerdeksler", value: '13' },
            { label: "Kamakselens doble lagerdeksel", value: '15' },
            { label: 'Kamakseltannhjulbolter', value: '47' },
            { label: 'Veivakselens tetningsringholder, bolter', value: '10' },
            { label: 'Veivakselens remskivebolt', value: '170' },
            { label: 'Ventildeksel, mutre/bolter', value: '9' },
            { label: 'Topplokkbolter:', header: true },
            { label: 'Trinn 1', value: '32', indent: true },
            { label: 'Trinn 2', value: '+180°', indent: true },
            { label: 'Motorfester:', header: true },
            { label: 'Venstre girkassefeste, bolter', value: '52', indent: true },
            { label: 'Bakre festebrakett-til-girkasse, bolter', value: '52', indent: true },
            { label: 'Bakre feste, gjennomgående bolt', value: '120', indent: true },
            { label: 'Høyre feste til motorstøtte, bolter', value: '24', indent: true },
            { label: 'Høyre feste til karosseri, bolter', value: '52', indent: true },
            { label: 'Tappeplugg motorolje', value: '30' },
            { label: 'Eksosgrenrør', value: '24' },
            { label: 'Svinghjulsbolter', value: '78' },
            { label: 'Drivstoffskinne-til-topplokk, bolter', value: '27' },
            { label: 'Tenningsspole, festebolter', value: '10' },
            { label: 'Innsugsmanifold, mutre', value: '30' },
            { label: 'Bankesensor', value: '20' },
            { label: 'Ramlagerdeksel, bolter:', header: true },
            { label: 'Trinn 1', value: '30', indent: true },
            { label: 'Trinn 2', value: '59', indent: true },
            { label: 'Oljefilterhus til sylinderblokk', value: '24' },
            { label: 'Oljetrykkbryter/-sensor', value: '15' },
            { label: 'Oljepumpe, festebolter', value: '9' },
            { label: 'Tennplugger', value: '25' },
            { label: 'Bunnpanne, bolter:', header: true },
            { label: 'Store bolter (x9)', value: '24', indent: true },
            { label: 'Små bolter (x6)', value: '10', indent: true },
            { label: 'Termostathus, mutter/bolt', value: '9' },
            { label: 'Kamkjededeksel, inspeksjonsplugg', value: '15' },
            { label: 'Kamkjededeksel:', header: true },
            { label: 'Bolter med mindre hode (x3)', value: '24', indent: true },
            { label: 'Bolter med større hode (x8)', value: '40', indent: true },
            { label: 'Kamkjede, fast føringsbolt', value: '10' },
            { label: 'Kamkjedestrammer, føringspivotbolt', value: '19' },
            { label: 'Kamkjedestrammer, festebolt', value: '12' },
            { label: 'Girkasse-til-motor, bolter', value: '64' },
            { label: 'Girkasse-til-motor, nedre plate bolter', value: '40' },
            { label: 'VVT-I oljekontrollventil, bolt', value: '10' },
            { label: 'Vannbypassrør, mutre/brakettbolter', value: '10' },
        ],
    },
    {
        title: 'Kjøling, varme & klimaanlegg',
        rows: [
            { label: 'Klimakompressor, festebolter', value: '25' },
            { label: 'Klimaanlegg rør, festebolter', value: '10' },
            { label: 'Tappeplugg kjølevæske', value: '20' },
            { label: 'Kjølevannspumpe, festebolter', value: '28' },
            { label: 'Kjølevæsketemperatursensor', value: '20' },
            { label: 'Termostatdeksel, mutter/bolt', value: '8' },
        ],
    },
    {
        title: 'Drivstoffsystem',
        rows: [
            { label: 'Kamakselposisjonssensor', value: '8' },
            { label: 'Veivakselposisjonssensor', value: '8' },
            { label: 'Drivstoffskinne-til-topplokk, bolter', value: '27' },
            { label: 'Drivstofftank, festebolter', value: '14' },
            { label: 'Innsugsmanifold, mutre/bolter', value: '19' },
            { label: 'MAP-sensor', value: '5' },
            { label: 'Gasspjeldhus, festebolter', value: '10' },
        ],
    },
    {
        title: 'Eksosanlegg',
        rows: [
            { label: 'Eksos midtseksjon-til-bakre lyddemper, klembolt', value: '32' },
            { label: 'Eksosgrenrør, mutre/bolter', value: '24' },
            { label: 'Eksosgrenrør, støttebrakett:', header: true },
            { label: 'Festebolt', value: '24', indent: true },
            { label: 'Festemutter', value: '19', indent: true },
            { label: 'Eksosgrenrør/katalysator-til-fremre rør, bolter', value: '45' },
            { label: 'Lambdasensor', value: '44' },
        ],
    },
    {
        title: 'Start- og ladesystem',
        rows: [
            { label: 'Generator:', header: true },
            { label: 'Øvre pivotbolt', value: '54', indent: true },
            { label: 'Nedre justeringsbrakettbolt', value: '34', indent: true },
            { label: 'Startmotor, festebolter', value: '37' },
            { label: 'Tappeplugg motorolje', value: '30' },
        ],
    },
    {
        title: 'Clutch',
        rows: [
            { label: 'Trykkplate-til-svinghjul, bolter', value: '19' },
        ],
    },
    {
        title: 'Girkasse',
        rows: [
            { label: 'Tappeplugg', value: '29' },
            { label: 'Motor-/girkassefester:', header: true },
            { label: 'Venstre feste, bolter', value: '52', indent: true },
            { label: 'Bakre feste, gjennomgående bolt', value: '120', indent: true },
            { label: 'Påfyllings-/nivåplugg', value: '39' },
            { label: 'Girvelger og skiftaktuator, festebolter', value: '18' },
            { label: 'Girspak, monteringsbolter', value: '12' },
            { label: 'Nøytralbryter (girinngrepssensor)', value: '40' },
            { label: 'Ryggelysbryter', value: '40' },
            { label: 'Startmotor, festebolter', value: '37' },
            { label: 'Girkasse turtallssensor', value: '8' },
            { label: 'Girkasse-til-motor, nedre plate bolter', value: '40' },
            { label: 'Girkasse-til-motor, bolter', value: '64' },
        ],
    },
    {
        title: 'Drivaksler',
        rows: [
            { label: 'Drivaksel, navmutter', value: '216' },
            { label: 'Nedre bærearm, kulepunkt mutter', value: '98' },
            { label: 'Hjulspindel-til-fjærbein, klembolt/mutter', value: '48' },
            { label: 'Styrestag, endemutter', value: '33' },
        ],
    },
    {
        title: 'Bremsesystem',
        rows: [
            { label: 'ABS hydraulikkenhet til karosseri', value: '19' },
            { label: 'ABS hjulsensor, festebolter', value: '8' },
            { label: 'Bremserør, koblinger', value: '15' },
            { label: 'Bremsekaliper, styrepinnebolter', value: '30' },
            { label: 'Bremsekaliper, slangekobling', value: '30' },
            { label: 'Bremsekaliper, festebrakett bolter', value: '89' },
            { label: 'Håndbrekkspak, festebolter', value: '22' },
            { label: 'Hovedsylinder-til-bremseforsterker, festebolter', value: '20' },
            { label: 'Bakre hjulsylinder, festebolt', value: '8' },
            { label: 'Bremseforsterker, skyvestang låsemutter', value: '22' },
            { label: 'Bremseforsterker-til-karosseri, festemutre', value: '20' },
        ],
    },
    {
        title: 'Forhjulsoppheng',
        rows: [
            { label: 'Krengningshemmer:', header: true },
            { label: 'Brakettbolter', value: '18', indent: true },
            { label: 'Koblingsstag, mutre', value: '18', indent: true },
            { label: 'Drivaksel (nav) mutter', value: '216' },
            { label: 'Nedre bærearm:', header: true },
            { label: 'Kulepunkt mutter', value: '98', indent: true },
            { label: 'Fremre pivotbolt', value: '100', indent: true },
            { label: 'Bakre festebolt', value: '100', indent: true },
            { label: 'Understellsramme, festebolter:', header: true },
            { label: 'Fremre bolter (sidechassisben)', value: '70', indent: true },
            { label: 'Bakre bolter (gulvpanel)', value: '48', indent: true },
            { label: 'Bakre bolter (nedre bærearm bakfeste)', value: '100', indent: true },
            { label: 'Fjærbein:', header: true },
            { label: 'Stempelstangmutter', value: '55', indent: true },
            { label: 'Toppfeste mutter', value: '55', indent: true },
            { label: 'Hjulspindel-til-fjærbein, klembolt/mutter', value: '48' },
        ],
    },
    {
        title: 'Bakhjulsoppheng',
        rows: [
            { label: 'Bakaksel bjelke-til-karosseri, festebolter', value: '123' },
            { label: 'Bakre nav, festebolter', value: '60' },
            { label: 'Støtdemper:', header: true },
            { label: 'Nedre festebolter', value: '48', indent: true },
            { label: 'Øvre festemutre', value: '25', indent: true },
        ],
    },
    {
        title: 'Styring',
        rows: [
            { label: 'Rattstamme, nedre knutepunkt klembolter', value: '35' },
            { label: 'Rattstamme, festebolter', value: '25' },
            { label: 'Rattstamme, beskyttelsesplate bolt', value: '25' },
            { label: 'Styresnekke, festebolter', value: '89' },
            { label: 'Rattmutter', value: '50' },
            { label: 'Styrestag ende:', header: true },
            { label: 'Kulepunkt mutter', value: '33', indent: true },
            { label: 'Låsemutre', value: '47', indent: true },
        ],
    },
    {
        title: 'Hjul',
        rows: [
            { label: 'Hjulmutre', value: '100' },
        ],
    },
    {
        title: 'Karosseri',
        rows: [
            { label: 'Dørstopper-til-A-stolpe, bolt', value: '27' },
            { label: 'Dørstopper-til-dør, bolter', value: '10' },
            { label: 'Ytre dørhåndtak, mutre', value: '5' },
            { label: 'Dørlås, bolter', value: '5' },
            { label: 'Setebelte, bolter', value: '42' },
            { label: 'Setefeste, bolter', value: '22' },
            { label: 'Vinduheis, festemutre', value: '7' },
        ],
    },
];
